# This workflow will do a clean installation of node dependencies, cache/restore them, run tests and build the source code.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
